server:
  port: 8081

spring:
  application:
    name: aws-contract-ecs-zip
  profiles:
    active: prod

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
