server:
  port: 8081

spring:
  application:
    name: aws-contract-ecs-zip

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

amazon:
  elb:
    contract: aws-contract-private-lb-2115797049.cn-northwest-1.elb.amazonaws.com.cn:8088
  s3:
    bucket: bq-zhy-contract-bucket
    zipPrefix: zip/
  ecs:
    cluster:
      name: default
    task:
      tag: bq
  sqs:
    queue:
      url: https://sqs.cn-northwest-1.amazonaws.com.cn/286792376082/aws-contract-queue
  sns:
    topic:
      arn: arn:aws-cn:sns:cn-northwest-1:286792376082:bq-aws
