server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: aws-contract-ecs-zip
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://lab.cxbwswfsjviz.rds.cn-northwest-1.amazonaws.com.cn:3306/labdb
    username: admin
    password: abcd1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

amazon:
  s3:
    bucket: bq-zhy-contract-bucket
    zipPrefix: zip/
  ecs:
    cluster:
      name: default
    task:
      tag: bq

## Mybatis
mybatis:
  type-aliases-package: com.aws.bq.model
  mapper-locations: classpath:mapper/*.xml

# PageHelper
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
  support-methods-arguments: true